### ISSUE TITLE
The SvIsCOW fallback define does not seem to work

### ISSUE THREAD

**Issue by ribasushi** [dankogai/p5-encode#13]
Encode 2.54 introduced this change: https://metacpan.org/diff/release/DANKOGAI/Encode-2.53/DANKOGAI/Encode-2.54#Encode.xs

It fails to compile on perl <= 5.8.2 with the following error:

```
cc -c  -I./Encode -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"2.54\" -DXS_VERSION=\"2.54\" -fpic "-I/home/rabbit/perl5/perlbrew/perls/5.8.2/lib/5.8.2/x86_64-linux-thread-multi-64int-ld/CORE"   Encode.c
Encode.xs: In function ‘XS_Encode__utf8_on’:
Encode.xs:852:16: error: called object is not a function or function pointer
     if (SvIsCOW(sv)) sv_force_normal(sv);
                ^
Encode.xs: In function ‘XS_Encode__utf8_off’:
Encode.xs:869:16: error: called object is not a function or function pointer
     if (SvIsCOW(sv)) sv_force_normal(sv);
                ^
make: *** [Encode.o] Error 1
```

Cheers
